name: versioneer
version: 0.1.0+6
description: A dart app to incremenent the version in a specified file.

# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  yaml: ^3.1.0